
all: code

code:
	g++ stl-code-containers.cpp   -o stl-code-containers
	g++ stl-code-cstddef.cpp      -o stl-code-cstddef
	g++ stl-code-ciso646.cpp      -o stl-code-ciso646
	g++ stl-code-adaptors.cpp     -o stl-code-adaptors
	g++ stl-code-copy-reverse.cpp -o stl-code-copy-reverse
	g++ stl-code-new.cpp          -o stl-code-new

clean:
	-@rm -f *.exe
	-@rm -f stl-code-containers
	-@rm -f stl-code-cstddef
	-@rm -f stl-code-ciso646
	-@rm -f stl-code-adaptors
	-@rm -f stl-code-copy-reverse
	-@rm -f stl-code-new

